repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff
        args: ["--fix", "--extend-select", "I"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'
    hooks:
      - id: mypy
        args: [--strict, --ignore-missing-imports]
        additional_dependencies: [tokenize-rt==3.2.0]
  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: ./.venv/bin/pytest tests
      language: system
      types: [python]
      pass_filenames: false
      always_run: true