# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup uv
        uses: astral-sh/setup-uv@v5.3.1
        with:
          python-version: "3.12"
          enable-cache: true
      - name: Install pip
        run: uv pip install pip
      - name: pre-commit
        run: |
          uv run pre-commit run ruff
          uv run pre-commit run ruff-format
          uv run pre-commit run mypy
      - name: pytest
        run: python -m pytest